# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('deleted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Person')),
                ('shared_with', models.ManyToManyField(related_name='shared_post_set', to='directory.Person')),
            ],
        ),
    ]
