# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('following', models.BooleanField()),
                ('location', models.CharField(max_length=254, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('last_updated', models.DateTimeField()),
                ('cert', models.TextField()),
                ('verified', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
